### ISSUE TITLE
Issue downloading the database

### ISSUE THREAD

**Issue by BenderFranziska** [egerber/spaCy-entity-linker#27]
Hi!

I had issues downloading the knowledge database: 

Running `python -m spacy_entity_linker "download_knowledge_base"` in the terminal, and also running the example code provided under the title 'USE'  resulted in the following error:

urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)>

I installed version 1.0.3, spacy 3.5.0 and python 3.11.

**Comment by MartinoMensio** [comment]
Hi @BenderFranziska,
This error is probably due to a wrong configuration of your machine (local issuer certificate / outdated SSL default certificates).
What is the output if you try to run this command?

```bash
wget https://huggingface.co/MartinoMensio/spaCy-entity-linker/resolve/main/knowledge_base.tar.gz
```
If the error persists, you may try to update your machine / SSL libraries. Depending on your OS this solution may be related https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate.

Best,
Martino

**Comment by BenderFranziska** [comment]
Hi Martino

It was indeed related to the stackoverflow-question you sent. I ran the Install Certificates.command and after that everything worked perfectly.
Thanks a lot!

Best,
Franziska
